[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@astrojs/netlify"

[context.production.environment]
  NODE_ENV = "production"
